name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  check:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3.0.0
    - run: ./bin/check-links
    - uses: shalzz/zola-deploy-action@v0.16.0
      env:
        BUILD_DIR: docs
        BUILD_ONLY: true
        BUILD_FLAGS: --drafts
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3.0.0
    - uses: shalzz/zola-deploy-action@v0.16.0
      env:
        BUILD_DIR: docs
        PAGES_BRANCH: gh-pages
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
